spring:
  application:
      name: eureka
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://zhangqi:1994@localhost:8761/eureka/
    fetch-registry: false
    allow-redirects: false
server:
  port: 8761

security:
  basic:
    enabled: true
  user:
    password: 1994
    name: zhangqi