spring:
  profiles:
    active: dev
  application:
      name: eureka
---
spring:
  profiles: dev
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://zhangqi:1994@localhost:8761/eureka/
    fetch-registry: false
    allow-redirects: false
server:
  port: 8761

security:
  basic:
    enabled: true
  user:
    password: 1994
    name: zhangqi
---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
server:
  port: 8762