spring:
  application:
      name: eureka
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://zhangqi:1994@localhost:8761/eureka/
    fetch-registry: false
    allow-redirects: false
    register-with-eureka: false
  server:
    enable-self-preservation: true
server:
  port: 8761

security:
  basic:
    enabled: true
  user:
    password: 1994
    name: zhangqi

#springboot 关闭应用
endpoints:
  shutdown:
    enabled: true
    sensitive: false
