spring:
  application:
      name: user-service

  datasource:
    name: mydb
    url: jdbc:mysql://localhost:3306/small?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1994
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  service-url:
      defaultZone: http://localhost:8761/eureka/  #注册到eureka
  instance:
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.onion.pojo

server:
  port: 8034

author:
  name: service