spring:
  application:
      name: user-service

  datasource:
    name: mydb
    url: jdbc:mysql://116.196.111.10:3306/small?useUnicode=true&characterEncoding=UTF-8
    username: zhangqi
    password: 1994
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://zhangqi:1994@localhost:8761/eureka/  #注册到eureka
    instance:
      prefer-ip-address: true

security:
  basic:
    enabled: false

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.onion.pojo

server:
  port: 8035

author:
  name: dev