spring:
  application:
      name: web

server:
  port: 8030
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
eureka:
  client:
    service-url:
      defaultZone: http://zhangqi:1994@localhost:8761/eureka/  #注册到eureka
    instance:
      prefer-ip-address: true

security:
  basic:
    enabled: false

author:
  name: 陆晨