spring:
  application:
      name: web
  retrofit:
    baseUrl: https://uhuishou.ronghezulin.com/loan-app/
  okhttp:
    connTimeOut: 11000
    netInterceptor[0]: com.onion.web.Interceptor.HttpLogger
    interceptor[0]: com.onion.web.Interceptor.HeaderInterceptor

server:
  port: 8033
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
eureka:
  client:
    service-url:
      defaultZone: http://zhangqi:1994@localhost:8761/eureka/  #注册到eureka
    instance:
      prefer-ip-address: true

feign:
  httpclient:
    connection-timeout: 100000
  hystrix:
    enabled: true

hystrix:
  metrics:
    enabled: true

security:
  basic:
    enabled: false

author:
  name: 张琦

