spring:
  application:
      name: web

server:
  port: 8033
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
eureka:
  service-url:
      defaultZone: http://localhost:8761/eureka/  #注册到eureka
  instance:
    prefer-ip-address: true

author:
  name: 张琦