spring:
  application:
    name: admin-server
server:
  port: 8062
eureka:
  client:
    service-url:
      defaultZone: http://zhangqi:1994@118.25.14.84:8761/eureka/  #注册到eureka
    instance:
      prefer-ip-address: true

security:
  basic:
    enabled: true
  user:
    name: zhangqi
    password: 1994

